import sys
print("Nate's Calculator v1.0       Made with python")
print(" ")
print("       mom gave me cola yipeeeeeeeeeeeeeee   ")
print(" ")
print("             #####################")
print("             ##  A   - use it - ##")
print("             ##  B   -  quit  - ##")
print("             #####################")
print(" ")
print(" ")
print("         Just one help text available        ")
print("                 Too lazy lol                ")
print(" ")
menuinput = (input("Press the buttons beside the options to select:"))
if menuinput == "A":
    print(" ")
    print("     Great, I have to not be lazy anymore :/ ")
    print(" ")
    print(" ")
    fn = int(input("First Number:"))
    op = (input("Operator, +, -, / or *:"))
    ln = int(input("The Second (last) number:"))
    print("hold on...")
    if op == "+":
        print("              ########################")
        print("              Result:", fn + ln)
        print("              ########################")
    elif op == "-":
        print("              ########################")
        print("              Result:", fn - ln)
        print("              ########################")
    elif op == "/":
        print("              ########################")
        print("              Result:", fn / ln)
        print("              ########################")
    elif op == "*":
        print("              ########################")
        print("              Result:", fn * ln)
        print("              ########################")
    else: print("Sorry that aint an operator, Could implement new stuff in 1.1")
elif menuinput == "B":
    print("See you next time.")
    sys.exit()
else: print("Sorry, That isnt an available option")